### ISSUE TITLE
[ReactNative]Duplicate module name: TouchHistoryMath

### ISSUE THREAD

**Issue by TinChak** [cuitianze/React-ReactNative-Redux_NOTEBOOK#4]
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: TouchHistoryMath
  Paths: /Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/react/lib/TouchHistoryMath.js collides with /Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: TouchHistoryMath
  Paths: /Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/react/lib/TouchHistoryMath.js collides with /Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:160:15)
    at /Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:125:25
```

**Comment by TinChak** [comment]
https://github.com/facebook/react-native/issues/5180

> issue 结尾说 0.22以后fix这个问题了，

升级下拭目以待吧，目前用的是0.21
