### ISSUE TITLE
[ReactNative]Failed to build DependencyGraph: @providesModule naming collision:   Duplicate module name: IOSDefaultEventPluginOrder

### ISSUE THREAD

**Issue by TinChak** [cuitianze/React-ReactNative-Redux_NOTEBOOK#5]
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: IOSDefaultEventPluginOrder
  Paths: /Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/react-native/Libraries/ReactIOS/IOSDefaultEventPluginOrder.js collides with /Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/react/lib/IOSDefaultEventPluginOrder.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: IOSDefaultEventPluginOrder
  Paths: /Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/react-native/Libraries/ReactIOS/IOSDefaultEventPluginOrder.js collides with /Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/react/lib/IOSDefaultEventPluginOrder.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:160:15)
    at /Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:125:25
Command /bin/sh failed with exit code 1

** BUILD FAILED **


The following build commands failed:
    PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images build/Build/Intermediates/tougudashi.build/Release-iphonesimulator/tougudashi.build/Script-00DD1BFF1BD5951E006B06BC.sh
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/tougudashi.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/tougudashi.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:469:13)
    at Object.execFileSync (child_process.js:489:13)
    at _runIOS (runIOS.js:91:34)
    at runIOS.js:24:5
    at tryCallTwo (/Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/react-native/local-cli/cli.js:87:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
```

**Comment by TinChak** [comment]
o(￣ヘ￣o#)  升级react-native版本困难重重啊。。。

[Node.JS: React Native Duplicate module name](http://ngnode.com/2016/05/05/node-js-react-native-duplicate-module-name/)

>  Solution :
> 
> Never mind – updating to React Native 26.0-rc fixes this issue since React 15.0.2 is now a dependency.

不行怪我咯，升级成0.26-rc，再不行就gg。
