### ISSUE TITLE
[ReactNative]Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by TinChak** [cuitianze/React-ReactNative-Redux_NOTEBOOK#6]
```
Installing build/Build/Products/Debug-iphonesimulator/tougudashi.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/tougudashi.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:469:13)
    at Object.execFileSync (child_process.js:489:13)
    at _runIOS (runIOS.js:91:34)
    at runIOS.js:24:5
    at tryCallTwo (/Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/cuitianze/Code/jobs/pangu_fe/app/node_modules/react-native/local-cli/cli.js:87:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
```

**Comment by TinChak** [comment]
没有找到debug目录，先在xcode里把target debug删了， 应该目前是只配置了release，没有配置debug
